services:

   db:
     image: mysql:8.0.43-debian
     container_name: mysql_db
     environment:
         MYSQL_ROOT_PASSWORD: password
         MYSQL_USER: appuser
         MYSQL_PASSWORD: app123 
         MYSQL_DATABASE: mydb 
     ports:
       - "3306:3306"
     volumes:
       - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
         