services:
  
  db:
     image: postgres:16
     container_name: postgres_db
     environment: 
        POSTGRES_USER: user 
        POSTGRES_PASSWORD: password
        POSTGRES_DB: prisma
     ports:
       - "5432:5432"
     volumes:
       - postgres_data:/var/lib/postgresql/postgres_data

volumes:
    postgres_data:     


